on:
  schedule:
    # Runs at 4 AM UTC (6 AM MESZ) and 5 AM UTC (6 AM MEZ)
    # Runs at 9 AM UTC (11 AM MESZ) and 10 AM UTC (11 AM MEZ)
    - cron: '0 4,5,9,10 * * *'

jobs:
  check_time:
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's 6 AM or 11 AM in Berlin
        run: |
          current_hour=$(TZ='Germany/Berlin' date +'%H')
          echo "Current hour in Berlin: $current_hour"
          if [ "$current_hour" == "08" ]; then
            echo "It's 8 AM! Running tasks..."
            echo "morning_run=true" >> $GITHUB_ENV
          fi
          if [ "$current_hour" == "11" ]; then
            echo "It's 11 AM! Running tasks..."
            echo "noon_run=true" >> $GITHUB_ENV
          fi

      - name: Execute Morning Tasks
        if: env.morning_run == 'true'
        run: echo "Executing morning tasks..."

      - name: Execute Noon Tasks
        if: env.noon_run == 'true'
        run: echo "Executing noon tasks..."
