
name: Run Mensa Bot with Python using Nix

# 30  6 * * 1-5 .../Mensa-Bot/mensabot/bin/python .../Mensa-Bot/mensa_bot.py > .../Mensa-Bot/output.log 2>&1
# 30 11 * * 1-5 .../Mensa-Bot/mensabot/bin/python .../Mensa-Bot/mensa_bot.py correct > .../Mensa-Bot/output.log 2>&1

on:
  schedule:
    - cron: "30 6,11 * * 1-5" # Monday to Friday at 6:30 and 11:30
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    name: Run Mensa Bot and upload menus file
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true

      - name: Initialize Nix
        run: nix develop --command echo "Setup complete"
      - name: Run Mensa Bot
        run: nix develop --command python3 mensa_bot.py
      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          path: mensa_bot.log
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    name: Deploy updated menu to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4