name: Get menus and deploy as webpage

on:
  schedule:
    # Runs at 4 AM UTC (5 AM MEZ / 6 AM MESZ)
    # and at 9 AM UTC (11 AM MESZ) and 10 AM UTC (11 AM MEZ)
    - cron: '0 4,9,10 * * 1-5'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    name: Run Mensa Bot, Upload & Deploy Pages
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
          check-outdated: false

      - name: Initialize Nix Flake
        run: nix develop --command echo "Setup complete"
      - name: Initialize mensa-api
        run: nix develop .#mensa-api --command bash -c "cd fetch_mensa; cargo build"
      - name: Run Mensa Bot
        run: nix develop --command python3 parse_menus.py
      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          path: parse_menus.log
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    name: Deploy updated menu to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
